// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortSession(arg1) {
  return window['go']['main']['App']['AbortSession'](arg1);
}

export function AddCustomLLMService(arg1) {
  return window['go']['main']['App']['AddCustomLLMService'](arg1);
}

export function ClearPrompt() {
  return window['go']['main']['App']['ClearPrompt']();
}

export function CreateSession(arg1, arg2) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2);
}

export function DeleteCustomLLMService(arg1) {
  return window['go']['main']['App']['DeleteCustomLLMService'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function FindFilesByName(arg1, arg2, arg3) {
  return window['go']['main']['App']['FindFilesByName'](arg1, arg2, arg3);
}

export function FindSymbol(arg1) {
  return window['go']['main']['App']['FindSymbol'](arg1);
}

export function FindText(arg1) {
  return window['go']['main']['App']['FindText'](arg1);
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetCommands() {
  return window['go']['main']['App']['GetCommands']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentProject() {
  return window['go']['main']['App']['GetCurrentProject']();
}

export function GetCustomLLMServices() {
  return window['go']['main']['App']['GetCustomLLMServices']();
}

export function GetFileContent(arg1) {
  return window['go']['main']['App']['GetFileContent'](arg1);
}

export function GetFileStatus() {
  return window['go']['main']['App']['GetFileStatus']();
}

export function GetFiles(arg1) {
  return window['go']['main']['App']['GetFiles'](arg1);
}

export function GetPath() {
  return window['go']['main']['App']['GetPath']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetProviderAuth() {
  return window['go']['main']['App']['GetProviderAuth']();
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetSessionChildren(arg1) {
  return window['go']['main']['App']['GetSessionChildren'](arg1);
}

export function GetSessionDetails(arg1) {
  return window['go']['main']['App']['GetSessionDetails'](arg1);
}

export function GetSessionDiff(arg1, arg2) {
  return window['go']['main']['App']['GetSessionDiff'](arg1, arg2);
}

export function GetSessionMessages(arg1, arg2) {
  return window['go']['main']['App']['GetSessionMessages'](arg1, arg2);
}

export function GetSessionStatus() {
  return window['go']['main']['App']['GetSessionStatus']();
}

export function GetSessionTodo(arg1) {
  return window['go']['main']['App']['GetSessionTodo'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetVCSInfo() {
  return window['go']['main']['App']['GetVCSInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function OpenCurrentDirectory() {
  return window['go']['main']['App']['OpenCurrentDirectory']();
}

export function RestartServer() {
  return window['go']['main']['App']['RestartServer']();
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}

export function RunCommandDetailed(arg1) {
  return window['go']['main']['App']['RunCommandDetailed'](arg1);
}

export function RunCommandDetailedWithCwd(arg1, arg2) {
  return window['go']['main']['App']['RunCommandDetailedWithCwd'](arg1, arg2);
}

export function SaveFileContent(arg1, arg2) {
  return window['go']['main']['App']['SaveFileContent'](arg1, arg2);
}

export function SendCustomLLMMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendCustomLLMMessage'](arg1, arg2, arg3);
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function SendMessageAsync(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendMessageAsync'](arg1, arg2, arg3, arg4);
}

export function StartOpenSpaceServer() {
  return window['go']['main']['App']['StartOpenSpaceServer']();
}

export function StopOpenSpaceServer() {
  return window['go']['main']['App']['StopOpenSpaceServer']();
}

export function SubmitPrompt() {
  return window['go']['main']['App']['SubmitPrompt']();
}

export function SummarizeSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['SummarizeSession'](arg1, arg2, arg3);
}

export function TestCustomLLMService(arg1) {
  return window['go']['main']['App']['TestCustomLLMService'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateCustomLLMService(arg1, arg2) {
  return window['go']['main']['App']['UpdateCustomLLMService'](arg1, arg2);
}

export function UpdateSession(arg1, arg2) {
  return window['go']['main']['App']['UpdateSession'](arg1, arg2);
}
