// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortSession(arg1:string):Promise<string>;

export function AddCustomLLMService(arg1:string):Promise<string>;

export function ClearPrompt():Promise<string>;

export function CreateFile(arg1:string):Promise<void>;

export function CreateFolder(arg1:string):Promise<void>;

export function CreateSession(arg1:string,arg2:string):Promise<string>;

export function DeleteCustomLLMService(arg1:string):Promise<string>;

export function DeletePath(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<string>;

export function FindFilesByName(arg1:string,arg2:string,arg3:number):Promise<string>;

export function FindSymbol(arg1:string):Promise<string>;

export function FindText(arg1:string):Promise<string>;

export function GetAgents():Promise<string>;

export function GetCommands():Promise<string>;

export function GetConfig():Promise<string>;

export function GetCurrentProject():Promise<string>;

export function GetCustomLLMServices():Promise<string>;

export function GetFileContent(arg1:string):Promise<string>;

export function GetFileStatus():Promise<string>;

export function GetFiles(arg1:string):Promise<string>;

export function GetPath():Promise<string>;

export function GetProjects():Promise<string>;

export function GetProviderAuth():Promise<string>;

export function GetProviders():Promise<string>;

export function GetServerStatus():Promise<string>;

export function GetSessionChildren(arg1:string):Promise<string>;

export function GetSessionDetails(arg1:string):Promise<string>;

export function GetSessionDiff(arg1:string,arg2:string):Promise<string>;

export function GetSessionMessages(arg1:string,arg2:string):Promise<string>;

export function GetSessionStatus():Promise<string>;

export function GetSessionTodo(arg1:string):Promise<string>;

export function GetSessions():Promise<string>;

export function GetVCSInfo():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListProviders():Promise<string>;

export function OpenCurrentDirectory():Promise<void>;

export function PickDirectory():Promise<string>;

export function RenamePath(arg1:string,arg2:string):Promise<void>;

export function RestartServer():Promise<void>;

export function RevealInExplorer(arg1:string):Promise<void>;

export function RunCommand(arg1:string):Promise<string>;

export function RunCommandDetailed(arg1:string):Promise<string>;

export function RunCommandDetailedWithCwd(arg1:string,arg2:string):Promise<string>;

export function SaveFileContent(arg1:string,arg2:string):Promise<void>;

export function SendCustomLLMMessage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SendMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SendMessageAsync(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SetWorkspaceDirectory(arg1:string):Promise<void>;

export function StartOpenSpaceServer():Promise<void>;

export function StopOpenSpaceServer():Promise<void>;

export function SubmitPrompt():Promise<string>;

export function SummarizeSession(arg1:string,arg2:string,arg3:string):Promise<string>;

export function TestCustomLLMService(arg1:string):Promise<string>;

export function UpdateConfig(arg1:string):Promise<string>;

export function UpdateCustomLLMService(arg1:string,arg2:string):Promise<string>;

export function UpdateSession(arg1:string,arg2:string):Promise<string>;
